### ISSUE TITLE
Not working on Gnome 3.32 /  ES6 classes

### ISSUE THREAD

**Issue by Zeph33** [petres/gnome-shell-extension-services-systemd#33]
Some recent changes in GS make this extension break with the following error:
gnome-shell[665]: JS ERROR: TypeError: this._construct is not a function
    newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
    _refresh/<@services-systemd@abteil.org/extension.js:79:31
    _refresh@extensions/services-systemd@abteil.org/extension.js:70:9
    wapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
   _createContainer/<@services-systemd@abteil.org extension.js:53:13

**Comment by petres** [comment]
should be fixed, thanks!
